"""Build report values from preserved G1/G2 evidence; no new method execution."""
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parents[2]
REPORTS = ROOT / 'task1/reports'
SOURCES = {
    'g2': 'task1/evidence/goal2/result_summary.json',
    'structure': 'task1/evidence/goal1/inventory/structure_summary.json',
    'ai': 'task1/evidence/goal2/a_epoch02/actual_ai_critique/actual_ai_critique.json',
    'counterexamples': 'task1/evidence/goal2/counterexamples/formal-02/synthetic_cases.json',
    'figures': 'task1/figures/goal2/figure_data.json',
}
DATA = {key: json.loads((ROOT / path).read_text()) for key, path in SOURCES.items()}
g2, st, ai = DATA['g2'], DATA['structure'], DATA['ai']
cs = next(v for v in g2['single_candidates'] if v['candidate'] == 'C-S')
r0 = next(v for v in g2['single_candidates'] if v['candidate'] == 'C-D')
direction_rows = {r['parameters']['direction']: r['summary']
                  for r in DATA['figures']['direction_threshold_and_neighborhood']['rows']}
if set(direction_rows) != {15, 25, 35, 45, 60} or any(r['n_records'] != 120 for r in direction_rows.values()):
    raise ValueError('HISTORICAL_DIRECTION_SCOPE_MISMATCH')
if len({r['common_covered_points'] for r in direction_rows.values()}) != 1:
    raise ValueError('DIRECTION_COMMON_COVERAGE_SENTENCE_CHANGED')

def tex(s):
    return str(s).replace('&', r'\&').replace('_', r'\_').replace('%', r'\%')

def number(n):
    return f'{n:,}' if isinstance(n, int) else f'{n:.3f}'

values = {
    'RawRecords': st['n_records'], 'RawPoints': st['n_points'],
    'RawEdges': st['edges_total'], 'ZeroDtEdges': st['zero_dt'],
    'SameTimeMoved': st['same_time_different_position'],
    'DuplicateEdges': st['consecutive_duplicate_position'],
    'LongGapEdges': st['long_gap_gt_30_source_seconds'],
    'DevelopmentConfigs': g2['parameters']['unique_development_configs'],
    'EvaluationConfigs': g2['parameters']['unique_evaluation_configs'],
    'GTwoEvalPoints': cs['n_input'], 'CSStrictRecords': cs['strict_gain_records'],
    'RZeroCovered': r0['common_covered_points'], 'CSCovered': cs['common_covered_points'],
    'AddedCovered': cs['common_covered_points'] - r0['common_covered_points'],
    'RZeroEmpty': r0['n_no_output_records'], 'CSEmpty': cs['n_no_output_records'],
    'RZeroFinal': r0['n_final'], 'CSFinal': cs['n_final'],
    'ValidModelCalls': g2['resource_accounting']['current_valid_model_costs']['visible_experiment_model_dispatches'],
    'HistoricModelCalls': g2['resource_accounting']['historical_model_costs']['visible_experiment_model_dispatches'],
    'MemoryDemo': g2['memory']['demonstration_records'],
    'SyntheticCases': g2['counterexamples']['synthetic_cases'],
    'KnownChecks': g2['counterexamples']['known_answer_checks'],
    'DirectionDevelopmentPoints': direction_rows[35]['n_input'],
    'DirectionLowRemoved': direction_rows[15]['n_direction_removed'],
    'DirectionRefRemoved': direction_rows[35]['n_direction_removed'],
    'DirectionHighRemoved': direction_rows[60]['n_direction_removed'],
    'DirectionCovered': direction_rows[35]['common_covered_points'],
}
macros = ['% Generated by ../build_history_sources.py; historical evidence only.']
for key, value in values.items():
    macros.append('\\newcommand{\\' + key + '}{' + number(value) + '}')
(REPORTS/'history_values.tex').write_text('\n'.join(macros)+'\n')

lines=[r'\begin{table}[H]',r'\centering\small',r'\caption{G2\_EVAL 的共同原始范围比较。共 120 条、\GTwoEvalPoints{} 点；工作米只表示固定数学模型内的长度。}',r'\begin{tabular}{lrr}',r'\toprule 指标 & R0 & C-S（G3 中称 S0） \\ \midrule']
fields=[('最终显式保留点','n_final'),('过滤点','n_filtered'),('方向删除点','n_direction_removed'),('DP 删除点','n_dp_removed'),('共同覆盖点','common_covered_points'),('共同误差超过 5 工作米的点','common_over_5_points'),('无输出记录','n_no_output_records'),('有输出原始窗口','raw_windows_covered'),('跨越原始断点的最终边','raw_break_crossings')]
for name,k in fields:
    lines.append(f'{name} & {number(r0[k])} & {number(cs[k])} '+r'\\')
lines += [f'P 即时输入最大误差 / 工作米 & {r0["dp_max_error"]:.6f} & {cs["dp_max_error"]:.6f} '+r'\\',f'共同 raw 最大误差 / 工作米 & {r0["common_max_error"]:.6f} & {cs["common_max_error"]:.6f} '+r'\\',r'\bottomrule\end{tabular}',r'\end{table}']
(REPORTS/'experiment1/history_candidate_table.tex').write_text('\n'.join(lines)+'\n')

lines=[r'\begin{table}[H]',r'\centering\small',r'\caption{G2 DEVELOPMENT 的六种顺序，均为 120 条记录。安全失败按记录计，其余按实际事件计。}',r'\begin{tabular}{lrrrrl}',r'\toprule 顺序 & 安全失败 & 跨原始断点边 & D 跨断点窗口 & P 删除断点触发点 & 结论 \\ \midrule']
labels={'NO_DEMONSTRATED_GAIN':'无新增收益','TRADEOFF':'权衡','REJECTED_BY_CONSTRAINT':'拒绝'}
for row in g2['orders']:
    if row['partition'] != 'DEVELOPMENT': continue
    vals=[row['order'],row['safety_failure_records'],row['raw_break_crossings'],row['direction_windows_across_raw_breaks'],row['p_removed_raw_break_trigger_points'],labels.get(row['research_status'],'拒绝')]
    lines.append(' & '.join(map(str,vals))+r' \\')
lines += [r'\bottomrule\end{tabular}',r'\end{table}']
(REPORTS/'experiment1/history_order_table.tex').write_text('\n'.join(lines)+'\n')

mode_names={'llm-only':'LLM only','search-only':'Search only','llm+search':'LLM + Search','llm+memory+search':'LLM + Memory + Search'}
lines=[r'\begin{table}[H]',r'\centering\small',r'\caption{G2 四模式实际执行。增益是通过保护且严格改善的锁定输出；分母为记录 $\times$ episode。时间为批次墙钟时间之和，不能当作每记录延迟。}',r'\begin{tabular}{llrrrr}',r'\toprule 分区 & 模式 & 增益 / 观察数 & 候选评估 & 可见模型调用 & 时间 / s \\ \midrule']
for part in ['DEVELOPMENT','G2_EVAL']:
    for mode in ['llm-only','search-only','llm+search','llm+memory+search']:
        row=next(x for x in g2['mode_summary'] if x['partition']==part and x['mode']==mode)
        label='开发' if part=='DEVELOPMENT' else 'G2 评估'
        vals=[label,mode_names[mode],f'{row["protected_gain_records_episodes"]}/{row["record_episode_observations"]}',row['candidate_evaluations'],row['experiment_model_dispatches'],f'{row["elapsed_batch_seconds_sum"]:.1f}']
        lines.append(' & '.join(map(str,vals))+r' \\')
    if part=='DEVELOPMENT': lines.append(r'\midrule')
lines += [r'\bottomrule\end{tabular}',r'\end{table}']
(REPORTS/'experiment1/history_modes_table.tex').write_text('\n'.join(lines)+'\n')

lines=[r'\begin{table}[H]',r'\centering\small',r'\caption{真实开发阶段模型建议的配对读数。误差单位为工作米；“原→候”依次表示参考 R0 与原样执行的合法提议。}',r'\begin{tabular}{lrrrr}',r'\toprule 原始建议 & 共同覆盖 / 原始点 & 共同最大误差 & P 输入点 & P 即时最大误差 \\ \midrule']
for entry in ai['actual_ai_citations']:
    if entry['citation_id'] not in ['AI-DEV-01','AI-DEV-02','AI-DEV-03','AI-DEV-05']: continue
    ref,cand=entry['reference_metrics'],entry['candidate_metrics']
    registered = entry['registered_comparison']
    same_mask = (registered is not None and registered['same_common_covered_point_mask']) or (ref['common_covered_points'] == cand['common_covered_points'] == ref['n_input'] == cand['n_input'])
    common = f'{ref["common_max_error"]:.3f} $\\to$ {cand["common_max_error"]:.3f}' if same_mask else '不可作同集合比较'
    vals=[entry['citation_id'],f'{ref["common_covered_points"]}$\\to${cand["common_covered_points"]}/{ref["n_input"]}',common,f'{ref["n_dp_input"]}$\\to${cand["n_dp_input"]}',f'{ref["dp_max_error"]:.3f}$\\to${cand["dp_max_error"]:.3f}']
    lines.append(' & '.join(vals)+r' \\')
lines += [r'\bottomrule\end{tabular}',r'\end{table}']
(REPORTS/'experiment1/history_ai_table.tex').write_text('\n'.join(lines)+'\n')
manifest={'classification':'REPORT_VALUES_FROM_PRESERVED_G1_G2_EVIDENCE','new_method_runs':0,'new_model_calls':0,'source_sha256':{p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in SOURCES.values()},'generated_files':{str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(REPORTS.glob('**/history*.tex'))},'values':values}
(ROOT/'task1/evidence/goal3/report_build/history_value_bindings.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'files':len(manifest['generated_files']),'source_files':len(SOURCES),'macro_values':len(values),'new_method_runs':0,'new_model_calls':0}))
